### ISSUE TITLE
Ability to add descriptions to individual papers

### ISSUE THREAD

**Issue by shivam-agarwal** [fabian-beck/survis#7]
How about the ability to add descriptions of individual papers in one's own words. It would be like a summary of what the user has understood.

**Comment by fabian-beck** [comment]
This feature is already there, just add to a bib entry:
"comment = {very nice paper!}"

The comment will be displayed below the abstract.

**Comment by shivam-agarwal** [comment]
Thanks, @fabian-beck, this is exactly the functionality I was looking for.
